// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCdPTAlnpH_taU7LhWSVcq6tzMoYiavs',
    appId: '1:656756887482:web:1def4df5160741b7099783',
    messagingSenderId: '656756887482',
    projectId: 'movie-2493b',
    authDomain: 'movie-2493b.firebaseapp.com',
    storageBucket: 'movie-2493b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vnXKdn6sBj-va9lhJvR73AyVWq_wtt0',
    appId: '1:656756887482:android:30adeb11f205257f099783',
    messagingSenderId: '656756887482',
    projectId: 'movie-2493b',
    storageBucket: 'movie-2493b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAatqntzo2m-GGrSSBwKeWE9B-r0WOdmF8',
    appId: '1:656756887482:ios:8f02592771bddf75099783',
    messagingSenderId: '656756887482',
    projectId: 'movie-2493b',
    storageBucket: 'movie-2493b.firebasestorage.app',
    iosBundleId: 'com.example.elDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAatqntzo2m-GGrSSBwKeWE9B-r0WOdmF8',
    appId: '1:656756887482:ios:8f02592771bddf75099783',
    messagingSenderId: '656756887482',
    projectId: 'movie-2493b',
    storageBucket: 'movie-2493b.firebasestorage.app',
    iosBundleId: 'com.example.elDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCdPTAlnpH_taU7LhWSVcq6tzMoYiavs',
    appId: '1:656756887482:web:a7eae8bb747bee94099783',
    messagingSenderId: '656756887482',
    projectId: 'movie-2493b',
    authDomain: 'movie-2493b.firebaseapp.com',
    storageBucket: 'movie-2493b.firebasestorage.app',
  );
}
